batch_size: 1
candidate: true
decay_epochs: 40
final_lr: 5.0e-06
init_lr: 1.0e-08
lr_after_warmup: 1.0e-05
max_audio_length: 246000
max_label_length: 256
mixed_precision: true
model_path: Models/10_wav2vec2_torch/202310231556
sort: true
top_k: 3
train_epochs: 60
train_workers: 20
vocab:
- ' '
- ''''
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
warmup_epochs: 10
weight_decay: 0.005
